name: ioSPI
channels:
  - conda-forge
  - defaults
dependencies:
  - codecov
  - coverage
  - flake8-black
  - flake8-docstrings
  - flake8-import-order
  - gemmi
  - mrcfile
  - numba
  - numpy
  - h5py>=2.10.0
  - pandas
  - pillow>=8.2.0
  - pip
  - pyfftw
  - pytest
  - pytest-cov
  - pytorch
  - pyyaml
  - pip:
    - black==20.8b0
    - pre-commit
    - starfile
